language: java
jdk:
  - oraclejdk11
before_install:
  - sudo apt-get update
  - cd app/
  - echo "Gerando o artefato com o Mavem!"
  - mvn clean package
  - cd ..
  - echo "Ir para a pasta do Docker!"
script:
  - docker-compose build
before_deploy:
  echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag docker-to-aws-with-java:latest cledjrb/docker-to-aws-with-java:latest;
    docker push cledjrb/docker-to-aws-with-java;
  on:
    branch: master
notifications:
  email: false